### ISSUE TITLE
Writing / Copying to DropBox in ChromeBook

### ISSUE THREAD

**Issue by alpha642** [yoichiro/chromeos-filesystem-dropbox#44]
This may have already been answered but I'm a "newbie" with ChromeOS.

LOVE that I can see my DropBox files -- but... I can't SAVE an attachment or copy a file to my DropBox in my Chromebook after I mount the App.  Is that how it's supposed to work?  Thanks.

**Comment by yoichiro** [comment]
@alpha642 If you tried to save the file from the Chrome Web browser, it has a known bug. It will be fixed after fixing by the Chrome development team.
Otherwise, that is, if you tried to save the file by some Chrome app (ex. Text, something image drawing app or etc), I confirmed the operation works today. Could you confirm the debug log on the console tab of the DevTools by the steps? https://github.com/yoichiro/chromeos-filesystem-dropbox/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by alpha642** [comment]
Thank you for your response.  I think I understand. 
 If I save an attachment out of the Chrome Browser on my Chromebook, I can't save it to DropBox.
I did not try any other Chrome apps.
Thank you for your time to respond.  I will wait until the Development Team addresses this bug.

**Comment by yoichiro** [comment]
@alpha642 I see. This issue is duplicated: #34 I close this issue.
